apiVersion: gateway.networking.k8s.io/v1
kind: Gateway

metadata:
  name: backend-gateway
  namespace: default

spec:
  gatewayClassName: approuting-istio

  infrastructure:
    annotations:
      service.beta.kubernetes.io/azure-dns-label-name: "deepak-aks-api-2509"

  listeners:
    - name: http
      protocol: HTTP
      port: 80

      allowedRoutes:
        namespaces:
          from: Same