apiVersion: gateway.networking.k8s.io/v1
kind: Gateway

metadata:
  name: backend-gateway
  namespace: default

spec:
  gatewayClassName: approuting-istio

  infrastructure:
    annotations:
      service.beta.kubernetes.io/azure-dns-label-name: "deepak-aks-api-2509"

  listeners:

    # Keep HTTP because cert-manager uses it for renewal/challenges
    - name: http
      protocol: HTTP
      port: 80

      allowedRoutes:
        namespaces:
          from: Same

    # HTTPS listener
    - name: https
      hostname: deepak-aks-api-2509.centralindia.cloudapp.azure.com
      protocol: HTTPS
      port: 443

      tls:
        mode: Terminate

        certificateRefs:
          - kind: Secret
            name: backend-tls

      allowedRoutes:
        namespaces:
          from: Same